/*--------------------------------------------------------------------------
 *  Copyright (c) 2010-2020, dennisit@163.com All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are
 * met:
 *
 * Redistributions of source code must retain the above copyright notice,
 * this list of conditions and the following disclaimer.
 * Redistributions in binary form must reproduce the above copyright
 * notice, this list of conditions and the following disclaimer in the
 * documentation and/or other materials provided with the distribution.
 * Neither the name of the suruonian developer nor the names of its
 * contributors may be used to endorse or promote products derived from
 * this software without specific prior written permission.
 *
 *  <dependency>
 *      <groupId>com.github.dennisit</groupId>
 *      <artifactId>floret</artifactId>
 *      <version>1.0.0</version>
 *  </dependency>
 *
 *  The code you see is generated by the generator "floret".
 *  // 生成路径
 *  String destPath = "/gen/";
 *  // 代码生成
 *  new FloretStrap().scanAnnoBorn(Settings.LOCATION_PATTERN, Settings.ACCEPT_SUFFIX, "com.dennisit", destPath, "UTF-8");
 *--------------------------------------------------------------------------
 */
var tinyKit = angular.module("tinyKit", []);

tinyKit.factory('$httpAjax', ['$http', function () {

    var factory = {};

    factory.post = function($http, reqUri, params, okCall, errorCall) {
        return _post($http, reqUri, params, okCall, errorCall);
    };

    factory.get = function($http, reqUri, params, okCall, errorCall) {
        return _get($http, reqUri, params, okCall, errorCall);
    };

    factory.getValue = function(params, key){
        return getValue(params, key);
    }
    return factory;

}]);

/**
 * post 操作
 * @param $http
 * @param reqUri
 * @param params
 * @param okCall
 * @param errorCall
 * @private
 */
function _post($http, reqUri, params, okCall, errorCall){
    console.log(reqUri);
    console.log(params);
    $http({
        url :  reqUri ,
        method : 'POST' ,
        data : params
    }).success(function (result) {
        console.log(result);
        okCall(result);
    }).error(function (result) {
        console.log("系统异常");
        errorCall(result);
    });
}

/**
 * get 操作
 * @param $http
 * @param reqUri
 * @param params
 * @param okCall
 * @param errorCall
 * @private
 */
function _get($http, reqUri, params, okCall, errorCall){
    console.log(reqUri);
    console.log(params);

    if(reqUri.indexOf("?")>0){
        reqUri = reqUri +"&";
    }else{
        reqUri = reqUri +"?";
    }
    $http({
        url :  reqUri + params,
        method : 'GET'
    }).success(function (result) {
        console.log(result);
        okCall(result);
    }).error(function (result) {
        console.log("系统异常");
        errorCall(result);
    });
}
